baseURL = "https://www.doubleopen.org/"
languageCode = "en-us"
title = "Double Open"
theme = "kube"
description = "Double Open is a company offering Open Source compliance solutions building on Open Source tools."
# Paginate = 5
[Params]
  RSSLink = "/index.xml"
  author = "Double Open" # add your company name
  github = "doubleopen-project" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""

[[menu.main]]
    name = "About"
    weight = -101
    url = "/about"
[[menu.main]]
    name = "News"
    weight = -100
    url = "/news"
[[menu.main]]
    name = "Case Studies"
    weight = -99
    url = "/case-studies"
[[menu.main]]
    name = "People & Contacts"
    weight = -97
    url = "/people"
