baseURL = "https://www.doubleopen.org/"
languageCode = "en-us"
title = "The Double Open Project"
theme = "kube"
description = "Double Open is a research project aiming to find out how to make open source compliance more open."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "The Double Open Project" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""

[[menu.main]]
    name = "About"
    weight = -101
    url = "/about"
[[menu.main]]
    name = "News"
    weight = -100
    url = "/news"
[[menu.main]]
    name = "Publications"
    weight = -99
    url = "https://github.com/doubleopen-project/doubleopen-publications"
[[menu.main]]
    name = "People & Contact"
    weight = -98
    url = "/people"

